export const DummyData = {
  dummyMovieData: {
    categories: ['Comedy', 'Sci-Fi', 'Action'],
    posterImage: 'https://i.imgur.com/hXgKBGQ.jpg',
    releaseYear: '2020',
    releaseDate: '2020-10-04T17:00:00.000Z',
    deleted: false,
    _id: '6102b74704750c2067f232b3',
    title: 'Avengers Endgame',
    synopsis:
      'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.',
    trailer: 'http://youtube.com/',
    director: 'Michael Bay',
    budget: 1000,
    featuredSong: 'JENG JENG',
    avgRating: 5,
    createdAt: '2021-07-29T14:12:23.761Z',
    updatedAt: '2021-07-29T14:12:23.761Z',
    __v: 0,
  },
  dummyMovieDataArrayed: [
    {
      categories: ['Comedy', 'Sci-Fi', 'Action'],
      posterImage: 'https://i.imgur.com/hXgKBGQ.jpg',
      releaseYear: '2020',
      releaseDate: '2020-10-04T17:00:00.000Z',
      deleted: false,
      _id: '6102b74704750c0067f232b3',
      title: 'Avengers Endgame',
      synopsis:
        'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.',
      trailer: 'http://youtube.com/',
      director: 'Michael Bay',
      budget: 1000,
      featuredSong: 'JENG JENG',
      avgRating: 5,
      createdAt: '2021-07-29T14:12:23.761Z',
      updatedAt: '2021-07-29T14:12:23.761Z',
      __v: 0,
    },
    {
      categories: ['Drama', 'Sci-Fi', 'Action'],
      posterImage: 'https://i.imgur.com/hXgKBGQ.jpg',
      releaseYear: '2021',
      releaseDate: '2020-10-04T17:00:00.000Z',
      deleted: false,
      _id: 'asfqfqwfqvw00dqw41241rc2',
      title: 'Dune',
      synopsis: `A mythic and emotionally charged hero's journey, "Dune" tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.`,
      trailer: 'http://youtube.com/',
      director: 'WONGFEHUNG',
      budget: 1000,
      featuredSong: 'JENG JENG PART 2',
      avgRating: 5,
      createdAt: '2021-07-29T14:12:23.761Z',
      updatedAt: '2021-07-29T14:12:23.761Z',
      __v: 0,
    },
    {
      categories: ['Drama', 'Thriller', 'Action'],
      posterImage: 'https://i.imgur.com/hXgKBGQ.jpg',
      releaseYear: '2021',
      releaseDate: '2020-10-04T17:00:00.000Z',
      deleted: false,
      _id: 'asds00asfqfq231v412x4451',
      title: 'The French Dispatch',
      synopsis: `A mythic and emotionally charged hero's journey, "Dune" tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.`,
      trailer: 'http://youtube.com/',
      director: 'Dedeq Roling',
      budget: 1000,
      featuredSong: 'JENG JENG PART 2',
      avgRating: 5,
      createdAt: '2021-07-29T14:12:23.761Z',
      updatedAt: '2021-07-29T14:12:23.761Z',
      __v: 0,
    },
    {
      categories: ['Drama', 'Thriller', 'Action'],
      posterImage: 'https://i.imgur.com/hXgKBGQ.jpg',
      releaseYear: '2021',
      releaseDate: '2020-10-04T17:00:00.000Z',
      deleted: false,
      _id: 'asdq2vqw1241v241x1415005',
      title: 'Midnight In The Switchgrass',
      synopsis: `A mythic and emotionally charged hero's journey, "Dune" tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.`,
      trailer: 'http://youtube.com/',
      director: 'Munandar Sokper',
      budget: 1000,
      featuredSong: 'JENG JENG PART 3',
      avgRating: 5,
      createdAt: '2021-07-29T14:12:23.761Z',
      updatedAt: '2021-07-29T14:12:23.761Z',
      __v: 0,
    },
    {
      categories: ['Comedy', 'Drama', 'Love'],
      posterImage: 'https://i.imgur.com/hXgKBGQ.jpg',
      releaseYear: '2021',
      releaseDate: '2020-10-04T17:00:00.000Z',
      deleted: false,
      _id: 'asdq2vqw1241v241x1400125',
      title: 'Roadrunner',
      synopsis: `A mythic and emotionally charged hero's journey, "Dune" tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.`,
      trailer: 'http://youtube.com/',
      director: 'Pak Ji Satpam',
      budget: 1000,
      featuredSong: 'JENG JENG PART 4',
      avgRating: 5,
      createdAt: '2021-07-29T14:12:23.761Z',
      updatedAt: '2021-07-29T14:12:23.761Z',
      __v: 0,
    },
  ],
  dummyMovieCategories: [
    'Action',
    'Drama',
    'Sci-Fi',
    'Animation',
    'Thriller',
    'Horror',
    'Comedy',
    'Red-Tape',
    'Adventure',
    'Sliceoflife',
    'Adult',
    'Kids',
    'Disaster',
    'War',
    'Crime',
  ],
};
